# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aspect_ratio.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        MainWindow.setMinimumSize(QtCore.QSize(350, 350))
        MainWindow.setMaximumSize(QtCore.QSize(350, 350))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.aspect_width = QtWidgets.QLineEdit(self.centralwidget)
        self.aspect_width.setGeometry(QtCore.QRect(70, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aspect_width.setFont(font)
        self.aspect_width.setObjectName("aspect_width")
        self.aspect_height = QtWidgets.QLineEdit(self.centralwidget)
        self.aspect_height.setGeometry(QtCore.QRect(190, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.aspect_height.setFont(font)
        self.aspect_height.setObjectName("aspect_height")
        self.label_colon = QtWidgets.QLabel(self.centralwidget)
        self.label_colon.setGeometry(QtCore.QRect(160, 40, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_colon.setFont(font)
        self.label_colon.setObjectName("label_colon")
        self.input_width = QtWidgets.QLineEdit(self.centralwidget)
        self.input_width.setGeometry(QtCore.QRect(140, 100, 113, 20))
        self.input_width.setObjectName("input_width")
        self.input_height = QtWidgets.QLineEdit(self.centralwidget)
        self.input_height.setGeometry(QtCore.QRect(140, 130, 113, 20))
        self.input_height.setObjectName("input_height")
        self.label_width = QtWidgets.QLabel(self.centralwidget)
        self.label_width.setGeometry(QtCore.QRect(80, 100, 47, 16))
        self.label_width.setObjectName("label_width")
        self.label_height = QtWidgets.QLabel(self.centralwidget)
        self.label_height.setGeometry(QtCore.QRect(80, 130, 47, 16))
        self.label_height.setObjectName("label_height")
        self.button_go = QtWidgets.QPushButton(self.centralwidget)
        self.button_go.setGeometry(QtCore.QRect(270, 110, 31, 31))
        self.button_go.setObjectName("button_go")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(70, 200, 201, 41))
        self.label_output.setText("")
        self.label_output.setObjectName("label_output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aspect Ratio Calculator"))
        self.aspect_width.setText(_translate("MainWindow", "16"))
        self.aspect_height.setText(_translate("MainWindow", "9"))
        self.label_colon.setText(_translate("MainWindow", ":"))
        self.label_width.setText(_translate("MainWindow", "Width"))
        self.label_height.setText(_translate("MainWindow", "Height"))
        self.button_go.setText(_translate("MainWindow", "Go"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
