# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aspect_ratio.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(214, 246)
        MainWindow.setMinimumSize(QtCore.QSize(214, 246))
        MainWindow.setMaximumSize(QtCore.QSize(214, 246))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_aspect_width = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_aspect_width.setGeometry(QtCore.QRect(20, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_aspect_width.setFont(font)
        self.lineEdit_aspect_width.setObjectName("lineEdit_aspect_width")
        self.lineEdit_aspect_height = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_aspect_height.setGeometry(QtCore.QRect(110, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_aspect_height.setFont(font)
        self.lineEdit_aspect_height.setObjectName("lineEdit_aspect_height")
        self.label_colon = QtWidgets.QLabel(self.centralwidget)
        self.label_colon.setGeometry(QtCore.QRect(100, 10, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_colon.setFont(font)
        self.label_colon.setObjectName("label_colon")
        self.lineEdit_width = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_width.setGeometry(QtCore.QRect(60, 50, 121, 20))
        self.lineEdit_width.setObjectName("lineEdit_width")
        self.lineEdit_height = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_height.setGeometry(QtCore.QRect(60, 80, 121, 20))
        self.lineEdit_height.setObjectName("lineEdit_height")
        self.label_width = QtWidgets.QLabel(self.centralwidget)
        self.label_width.setGeometry(QtCore.QRect(20, 50, 47, 16))
        self.label_width.setObjectName("label_width")
        self.label_height = QtWidgets.QLabel(self.centralwidget)
        self.label_height.setGeometry(QtCore.QRect(20, 80, 47, 16))
        self.label_height.setObjectName("label_height")
        self.pushButton_multiplier = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_multiplier.setGeometry(QtCore.QRect(20, 120, 61, 21))
        self.pushButton_multiplier.setObjectName("pushButton_multiplier")
        self.label_output = QtWidgets.QLabel(self.centralwidget)
        self.label_output.setGeometry(QtCore.QRect(20, 150, 161, 41))
        self.label_output.setText("")
        self.label_output.setObjectName("label_output")
        self.lineEdit_multiplier = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_multiplier.setGeometry(QtCore.QRect(100, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_multiplier.setFont(font)
        self.lineEdit_multiplier.setText("")
        self.lineEdit_multiplier.setObjectName("lineEdit_multiplier")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 214, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Aspect Ratio Calculator"))
        self.lineEdit_aspect_width.setText(_translate("MainWindow", "16"))
        self.lineEdit_aspect_height.setText(_translate("MainWindow", "9"))
        self.label_colon.setText(_translate("MainWindow", ":"))
        self.label_width.setText(_translate("MainWindow", "Width"))
        self.label_height.setText(_translate("MainWindow", "Height"))
        self.pushButton_multiplier.setText(_translate("MainWindow", "Multiplier"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
